/**
 * @stellaronramp/identity — off-chain BBS+ KYC credentials.
 *
 * Pure TypeScript. No chain access, no network calls, no PII storage. The gateway calls
 * `issue()`, the holder's SDK calls `prove()`/`derive()`, a relying party or the on-chain
 * verifier calls `verify()`/`checkPredicate()`.
 *
 * signed by the issuer, not a range proof over a date of birth, and that is a load-bearing
 * decision rather than a shortcut.
 */

export {
  CIPHERSUITE,
  CLAIM_INDEX,
  CLAIM_SPECS,
  CLAIM_SPEC_BY_INDEX,
  CREDENTIAL_HEADER,
  ISSUER_JURISDICTION_POLICY,
  MAX_SCHEMA_ATTRIBUTES,
  SCHEMA_ATTRIBUTE_COUNT,
  SCHEMA_VERSION,
  SUBJECT_BINDING_SALT_BYTES,
  SchemaError,
  assertNoPiiDisclosed,
  computeSubjectBinding,
  decodeDisclosed,
  encodeClaim,
  encodeClaims,
  normalizeIndexes,
  type ClaimIndex,
  type ClaimKind,
  type ClaimName,
  type ClaimSpec,
  type ClaimValue,
  type KycClaims,
} from './schema.js';

export {
  BINDING_DOMAIN,
  BindingError,
  NONCE_BYTES,
  PRESENTATION_HEADER_DOMAIN,
  PROOF_MAX_WINDOW,
  ReplayGuard,
  assertValidBinding,
  bindingDigest,
  bindingDigestHex,
  bindingsEqual,
  canonicalBindingBytes,
  presentationHeaderFor,
  randomNonce,
  type ProofBinding,
} from './binding.js';

export {
  FP_BYTES,
  G1_COMPRESSED_BYTES,
  G1_UNCOMPRESSED_BYTES,
  G2_COMPRESSED_BYTES,
  G2_UNCOMPRESSED_BYTES,
  PointError,
  SCALAR_BYTES,
  SIGNATURE_BYTES,
  compressG1,
  compressG2,
  decompressG1,
  decompressG2,
  expectedProofBytes,
  flattenSorobanProof,
  splitProof,
  splitSignature,
  toHex,
  undisclosedCountFromProofBytes,
  type SorobanProof,
  type SorobanSignature,
} from './points.js';

export {
  BBS_API_ID,
  BBS_GENERATOR_COUNT,
  GENERATORS_ROOT_ENCODING,
  GeneratorError,
  bbsGenerators,
  createGenerators,
  type BbsGenerators,
} from './generators.js';

export {
  CredentialError,
  ISSUANCE_CLOCK_SKEW_SECONDS,
  UNSAFE_NO_CHECKS,
  UNSAFE_SKIP,
  derive,
  deserializeCredential,
  deserializeProof,
  disclosedClaimNames,
  generateIssuerKeyPair,
  issue,
  issuerIdFromPublicKey,
  issuerPublicKey,
  serializeCredential,
  serializeProof,
  verify,
  verifyCredential,
  verifyDetailed,
  type Credential,
  type IssuerKeyPair,
  type Proof,
  type SerializedCredential,
  type SerializedProof,
  type UnsafeSkip,
  type VerifyFailure,
  type VerifyOptions,
  type VerifyResult,
} from './credential.js';

export {
  MAX_STATUS_LIST_BYTES,
  MINIMUM_STATUS_LIST_BYTES,
  MINIMUM_STATUS_LIST_ENTRIES,
  MULTIBASE_BASE64URL_NOPAD_PREFIX,
  STATUS_PURPOSES,
  StatusListError,
  base64urlDecode,
  base64urlEncode,
  bitAt,
  decodeStatusList,
  encodeStatusList,
  isStatusSet,
  multibaseDecode,
  statusAt,
  type BitstringStatusList,
  type DecodeStatusListOptions,
  type DecodedStatusList,
  type EncodeStatusListOptions,
  type StatusListRequest,
  type StatusListResolver,
  type StatusMessage,
  type StatusPurpose,
} from './status-list.js';

export {
  DISCLOSABLE_CLAIM_NAMES,
  PredicateError,
  allOf,
  checkPredicate,
  claimPredicate,
  countryAllowed,
  credentialAudit,
  gateOnrampPredicate,
  gatePredicateFor,
  livenessOk,
  notPep,
  notSanctioned,
  over18,
  over21,
  prove,
  standardOnrampPredicate,
  type CountryAllowedOptions,
  type DisclosableClaimName,
  type Predicate,
} from './predicates.js';
