/**
 * A SOFTWARE P-256 WebAuthn authenticator on `node:crypto`, injectable into
 * `PasskeyKitConfig.WebAuthn`.
 *
 * ╔══════════════════════════════════════════════════════════════════════════╗
 * ║  TEST / DEVELOPMENT ONLY. NEVER A PRODUCTION PATH.                        ║
 * ║                                                                            ║
 * ║  - NON-ATTESTED: a real platform authenticator carries an attestation     ║
 * ║    statement chaining the key to genuine hardware. This one carries an    ║
 * ║    empty attestation object, and the passkey wallet contract does not     ║
 * ║    check attestations at all (its error space, codes 120-126, checks      ║
 * ║    clientDataJSON shape, challenge binding, and flags — nothing about     ║
 * ║    provenance).                                                           ║
 * ║  - EXTRACTABLE KEYS: the P-256 private key is generated by                ║
 * ║    `node:crypto.generateKeyPairSync` inside an ordinary process and is    ║
 * ║    EXPORTED here (`privateKeyPem`) so tests can verify assertions. A      ║
 * ║    "passkey" whose private key can be printed is not a passkey; it is a   ║
 * ║    software key with extra steps.                                         ║
 * ╚══════════════════════════════════════════════════════════════════════════╝
 *
 * Why it exists at all: `PasskeyKitConfig.WebAuthn` is a documented injection point ("Custom
 * WebAuthn implementation (for testing)" — passkey-kit dist/kit.d.ts), and driving it with this
 * authenticator makes the whole create→deploy→connect flow runnable HEADLESS. Proven end-to-end
 * on live testnet four times before this module was written (passkey-kit-EXECUTED-ADDENDUM.md §1:
 * four separate wallets, all deployed, signer reported `Secp256r1/live/persistent` by Mercury).
 * This file is that proven harness (`harness/t2.mjs`) promoted into typed TypeScript, byte
 * semantics unchanged.
 *
 * Assertion semantics (what the wallet contract's `__check_auth` actually checks — codes 120-126):
 * clientDataJSON ≤ 1024 B and parseable JSON, `challenge == base64url(payload)`,
 * `type == "webauthn.get"`, authenticatorData ≥ 37 B, UP flag REQUIRED, UV NOT required. This
 * authenticator sets flags 0x05 (UP|UV), which satisfies both readings.
 */

import {
  createHash,
  createPrivateKey,
  createPublicKey,
  generateKeyPairSync,
  randomBytes,
  sign as cryptoSign,
  type KeyObject,
} from 'node:crypto';

import type { KitWebAuthnClient } from './kit-types.js';

export class SoftwareAuthenticatorError extends Error {
  override readonly name = 'SoftwareAuthenticatorError';
}

const b64u = (b: Uint8Array | Buffer): string => Buffer.from(b).toString('base64url');

export interface SoftwareP256Options {
  /** WebAuthn Relying Party id (a domain). Must match what the kit was constructed with. */
  readonly rpId?: string;
  /** Origin written into clientDataJSON. Must match the RP id's scheme. */
  readonly origin?: string;
  /**
   * Supply an existing PKCS#8 PEM private key instead of generating one (test replay fixtures).
   * The matching SPKI public key is re-derived from it.
   */
  readonly privateKeyPem?: string;
}

/** What the factory hands back: the kit-compatible client PLUS its (extractable) material. */
export interface SoftwareP256Authenticator extends KitWebAuthnClient {
  /** The Relying Party id this authenticator answers for. */
  readonly rpId: string;
  readonly origin: string;
  /** DER-encoded SPKI public key — the same bytes handed over during registration. */
  readonly publicKeySpki: Uint8Array;
  /** PKCS#8 PEM private key. Extractable BY DESIGN; see the TEST/DEV ONLY block above. */
  readonly privateKeyPem: string;
  /** base64url credential id, stable across registration and assertions. */
  readonly credentialId: string;
}

/**
 * Build one authenticator instance. Each call generates (or adopts) exactly ONE key and ONE
 * credential id; a test simulating two wallets constructs two instances.
 */
export function softwareP256WebAuthn(options: SoftwareP256Options = {}): SoftwareP256Authenticator {
  const rpId = options.rpId ?? 'example.com';
  const origin = options.origin ?? `https://${rpId}`;
  if (!/^https:\/\//.test(origin)) {
    throw new SoftwareAuthenticatorError(
      `origin must be https (${origin}) — this authenticator models a real one`,
    );
  }

  let privateKey: KeyObject;
  let publicKey: KeyObject;
  if (options.privateKeyPem !== undefined) {
    privateKey = createPrivateKey(options.privateKeyPem);
    publicKey = createPublicKey(privateKey);
  } else {
    const pair = generateKeyPairSync('ec', { namedCurve: 'prime256v1' });
    privateKey = pair.privateKey;
    publicKey = pair.publicKey;
  }

  const spki = new Uint8Array(publicKey.export({ type: 'spki', format: 'der' }));
  const pkcs8 = privateKey.export({ type: 'pkcs8', format: 'pem' });
  const credId = randomBytes(32);
  const rpIdHash = createHash('sha256').update(rpId).digest();

  /** 37 bytes: sha256(rpId) ‖ flags(UP|UV) ‖ signCount(0). The contract requires ≥37 B and UP. */
  const authenticatorData = (): Buffer =>
    Buffer.concat([rpIdHash, Buffer.from([0x05]), Buffer.alloc(4)]);

  return {
    rpId,
    origin,
    publicKeySpki: spki,
    privateKeyPem: String(pkcs8),
    credentialId: b64u(credId),

    async startRegistration({ optionsJSON }) {
      const clientDataJSON = Buffer.from(
        JSON.stringify({
          type: 'webauthn.create',
          challenge: optionsJSON.challenge,
          origin,
        }),
      );
      return {
        id: b64u(credId),
        rawId: b64u(credId),
        type: 'public-key',
        clientExtensionResults: {},
        response: {
          clientDataJSON: b64u(clientDataJSON),
          // Empty attestation object: see NON-ATTESTED above. The kit reads `publicKey`
          // (SPKI) out of the response and normalizes it via crypto.subtle itself.
          attestationObject: b64u(Buffer.alloc(0)),
          publicKey: b64u(spki),
          authenticatorData: b64u(authenticatorData()),
        },
      };
    },

    async startAuthentication({ optionsJSON }) {
      if (typeof optionsJSON.challenge !== 'string' || optionsJSON.challenge.length === 0) {
        throw new SoftwareAuthenticatorError('authentication options carry no challenge');
      }
      const authData = authenticatorData();
      const clientDataJSON = Buffer.from(
        JSON.stringify({
          type: 'webauthn.get',
          challenge: optionsJSON.challenge, // == base64url(signature payload); checked on chain
          origin,
        }),
      );
      // Signature covers authenticatorData ‖ sha256(clientDataJSON) — the WebAuthn assertion
      // layout. DER-encoded here; the kit compacts it to 64-byte r‖s before use.
      const signedMessage = Buffer.concat([
        authData,
        createHash('sha256').update(clientDataJSON).digest(),
      ]);
      const derSig = cryptoSign('sha256', signedMessage, privateKey);
      return {
        id: b64u(credId),
        rawId: b64u(credId),
        type: 'public-key',
        clientExtensionResults: {},
        response: {
          authenticatorData: b64u(authData),
          clientDataJSON: b64u(clientDataJSON),
          signature: b64u(derSig),
        },
      };
    },
  };
}
